routes/web.php
<?php

use App\Models\Service;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Artisan;

Route::get('/clear', function () {
    $output = new \Symfony\Component\Console\Output\BufferedOutput();
    Artisan::call('optimize:clear', array(), $output);
    return $output->fetch();
})->name('/clear');



Route::get('queue-work', function () {
    return Illuminate\Support\Facades\Artisan::call('queue:work', ['--stop-when-empty' => true]);
});
Route::get('schedule-run', function () {
    return Illuminate\Support\Facades\Artisan::call('schedule:run');
});

Route::get('cron', 'FrontendController@cron')->name('cron');
Route::get('/get-player-name/{playerId}/{game}', 'CustomProviderController@getPlayerName')->name('get-player-name');


Route::get('/user', 'Auth\LoginController@showLoginForm')->name('login');
Auth::routes(['verify' => true]);
Route::get('/registerAsAgent', 'Agent\HomeController@showAgentRegistrationForm')->name('registerAsAgent');
Route::Post('/registerAsAgent/{user}', 'Agent\HomeController@registerAsAgent')->name('addAgent');


Route::group(['middleware' => ['auth'], 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('/check', 'VerificationController@check')->name('check');
    Route::get('/resend_code', 'VerificationController@resendCode')->name('resendCode');
    Route::post('/mail-verify', 'VerificationController@mailVerify')->name('mailVerify');
    Route::post('/sms-verify', 'VerificationController@smsVerify')->name('smsVerify');
    Route::middleware('userCheck')->group(function () {
        Route::get('/dashboard', 'User\ServiceController@index')->name('home');
//        Route::get('/dashboard', 'HomeController@index')->name('home');
        Route::get('use_spare_balance', 'HomeController@use_spare_balance')->name('use_spare_balance');
        Route::get('add-fund', 'HomeController@addFund')->name('addFund');
        Route::post('add-fund', 'PaymentController@addFundRequest')->name('addFund.request');
        Route::get('addFundConfirm', 'PaymentController@depositConfirm')->name('addFund.confirm');
        Route::post('addFundConfirm', 'PaymentController@fromSubmit')->name('addFund.fromSubmit');

        Route::get('balance-transfer', 'HomeController@transferBalance')->name('balance.transfer');
        Route::post('transfer', 'HomeController@transfer')->name('balance-transfer');

        //transaction
        Route::get('/transaction', 'HomeController@transaction')->name('transaction');
        Route::get('/transaction-search', 'HomeController@transactionSearch')->name('transaction.search');
        Route::get('fund-history', 'HomeController@fundHistory')->name('fund-history');
        Route::get('fund-history-search', 'HomeController@fundHistorySearch')->name('fund-history.search');
        Route::get('/use-balance-coupon', 'HomeController@useBalanceCoupon')->name('use-balance-coupon');
        Route::Post('/add-balance-coupon', 'HomeController@addBalanceCoupon')->name('add-balance-coupon');

        Route::get('/user/debts', 'User\HomeController@debts')->name('debts');
        Route::get('/getLevelData', 'User\HomeController@getLevelData')->name('getLevelData');


        Route::get('/profile', 'HomeController@profile')->name('profile');
        Route::post('/updateProfile', 'HomeController@updateProfile')->name('updateProfile');
        Route::put('/updateInformation', 'HomeController@updateInformation')->name('updateInformation');
        Route::post('/updatePassword', 'HomeController@updatePassword')->name('updatePassword');

        Route::get('/apiKey', 'HomeController@apiKey')->name('apiKey');

        //order
        Route::resource('order', 'User\OrderController');
        Route::get('/orders', 'User\OrderController@search')->name('order.search');
        Route::post('/order/status', 'User\OrderController@statusChange')->name('order.status.change');
        Route::get('/orders/{status}', 'User\OrderController@statusSearch')->name('order.status.search');
        Route::get('/mass/orders', 'User\OrderController@massOrder')->name('order.mass');
        Route::post('/mass/orders', 'User\OrderController@masOrderStore')->name('order.mass.store');
        Route::get('/get-service', 'ServiceController@getservice')->name('get.service');

        //order search
        Route::get('/services', 'User\ServiceController@index')->name('service.show');
        Route::get('/products', 'User\ServiceController@show')->name('products');
        Route::get('/service-search', 'User\ServiceController@search')->name('service.search');
        Route::get('/services/{id}', 'User\ServiceController@service')->name('services.show');
        Route::get('/player/{serviceid}/{playerid}', 'User\ServiceController@getPlayerName')->name('service.player');

        Route::get('/api/docs', 'User\ApiController@index')->name('api.docs');
        Route::post('/keyGenerate', 'User\ApiController@apiGenerate')->name('keyGenerate');
        Route::get('checksms/{id}', 'ApiProviderController@checkSMS')->name('checksms');
        Route::group(['prefix' => 'ticket', 'as' => 'ticket.'], function () {
            Route::get('/', 'User\SupportController@index')->name('list');
            Route::get('/create', 'User\SupportController@create')->name('create');
            Route::post('/create', 'User\SupportController@store')->name('store');
            Route::get('/view/{ticket}', 'User\SupportController@view')->name('view');
            Route::put('/reply/{ticket}', 'User\SupportController@reply')->name('reply');
            Route::get('/download/{ticket}', 'User\SupportController@download')->name('download');
        });

        Route::post('/service', function (Request $request) {
            $parent_id = $request->cat_id;
            $services = Service::where('category_id', $parent_id)->where('service_status', 1)->get();
            return response()->json($services);
        })->name('service');


        Route::get('push-notification-show', 'SiteNotificationController@show')->name('push.notification.show');
        Route::get('push.notification.readAll', 'SiteNotificationController@readAll')->name('push.notification.readAll');
        Route::get('push-notification-readAt/{id}', 'SiteNotificationController@readAt')->name('push.notification.readAt');

        Route::get('/user-service', 'User\OrderController@userservice')->name('service_id');

        Route::get('points', 'HomeController@pointTransactions')->name('points');
        Route::get('/points-search', 'HomeController@pointTransactionsSearch')->name('points.transactions.search');
        Route::post('points-replace', 'HomeController@replacePoints')->name('points.replace');

        //Marketer
        Route::middleware('can:join_as_marketer')->group(function () {
            Route::get('marketer-join', 'MarketerController@create')->name('marketer.join');
            Route::post('marketer-join', 'MarketerController@store')->name('marketer.store');
            Route::get('random-code', 'MarketerController@getRandomInvitaionCode')->name('marketer.random-code');
            Route::post('marketer-golden-join', 'MarketerController@goldenMarketer')->name('marketer.golden.store');
        });
        Route::middleware('can:marketer')->group(function () {
            Route::get('marketers', 'MarketerController@index')->name('marketers');
            Route::middleware('can:active_marketer')->group(function () {
                Route::post('swap', 'MarketerController@swap')->name('marketer.swap')->middleware('can:normal_marketer');
                Route::post('marketer-golden-refund', 'MarketerController@goldenMareketerRefund')->name('marketer.golden.refund')->middleware('can:golden_marketer');
            });


        });
        Route::post('username', 'HomeController@getUsernameByEmail')->name('user.username');
    });
});
Route::group(['middleware' => ['auth', 'can:agent'], 'prefix' => 'agent', 'as' => 'agent.'], function () {
    Route::middleware('userCheck')->group(function () {
        Route::get('/users', 'Agent\UserController@index')->name('users');
        Route::get('/products', 'Agent\ServiceController@show')->name('products');
        Route::get('/users/search', 'Agent\UserController@search')->name('users.search');
        Route::get('/user/create', 'Agent\UserController@create')->name('user.create');
        Route::post('/user/create', 'Agent\UserController@store')->name('user.store');
        Route::get('/user/edit/{id}', 'Agent\UserController@userEdit')->name('user.edit');
        Route::post('/user/update/{id}', 'Agent\UserController@userUpdate')->name('user.update');
        Route::get('/user/add-balance', 'Agent\UserController@addBalance')->name('user.add-balance');
        Route::post('/user/add-balance', 'Agent\UserController@addBalanceToUser')->name('user.add-balance-to-user');
        Route::get('use_spare_balance', 'Agent\HomeController@use_spare_balance')->name('use_spare_balance');
        Route::get('/add-debt-payment', 'Agent\UserController@addDebtPayment')->name('add-debt-payment');
        Route::Post('/pay-a-debt', 'Agent\UserController@payDebt')->name('pay-a-debt');
        //order search
        Route::get('/services', 'Agent\ServiceController@index')->name('service.show');
        Route::get('/service-search', 'Agent\ServiceController@search')->name('service.search');
        Route::get('/services/{id}', 'Agent\ServiceController@service')->name('services.show');

        Route::get('/users/orders', 'Agent\UserController@usersOrder')->name('users.orders');
        Route::get('/users/orderSearch', 'Agent\UserController@usersOrderSearch')->name('users.OrderSearch');

        Route::get('/users/debtSearch', 'Agent\UserController@usersDebtSearch')->name('users.debtSearch');

        Route::get('/profile', 'Agent\HomeController@profile')->name('profile');

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public $appends = ['provider_name'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    public function service_code()
    {
        return $this->hasMany(ServiceCode::class, 'service_id', 'id');
    }


    public function service_price_ranges()
    {
        return $this->hasMany(ServicePriceRange::class, 'service_id');
    }
    public function provider()
    {
        return $this->belongsTo(ApiProvider::class, 'api_provider_id', 'id');
    }

    public function orders()
    {
        return $this->hasMany(Order::class, 'service_id','id');
    }

    protected function scopeUserRate($query)
    {
        $query->addSelect(['user_rate' => UserServiceRate::select('price')
            ->whereColumn('service_id', 'services.id')
            ->where('user_id', auth()->id())
        ]);
    }

    public function getProviderNameAttribute($value)
    {
        if(isset($this->api_provider_id) && $this->api_provider_id != 0){
            $prov = ApiProvider::find($this->api_provider_id);
            if($prov){
                return $prov['api_name'] ;
            }
            return false;
        }
    }
}

app/Http/Controllers/Agent/ServiceController.php
<?php

namespace App\Http\Controllers\Agent;

use App\Http\Controllers\Controller;
use App\Models\AgentCommissionRate;
use App\Models\Category;
use App\Models\Fund;
use App\Models\Order;
use App\Models\Service;
use App\Models\Transaction;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;

class ServiceController extends Controller
{
    public function index()
    {
        $categories = Category::with(['service' => function ($query) {
            $query->userRate()->where('service_status', 1);
        }])
            ->where('status', 1)
            ->get();
        $user = Auth::user();
        if ($user->is_agent == 1 && $user->is_approved == 1){
            $transactions = Transaction::where('user_id',$user->id)->get();
            $commissions = AgentCommissionRate::whereMonth('created_at', date('m'))
                ->whereYear('created_at', date('Y'))
                ->get();
//            dd($commissions);
            $commission_rate = 0;
            foreach ($commissions as $commission){
                $commission_rate +=  $commission->commission_rate;
            }
            $total = Fund::where('user_id', $user->id)->where('status', 1)->sum('amount');
            return view('agent.pages.services.show-service',compact('transactions','commission_rate','total','categories'));
        }elseif ($user->is_agent == 1 && $user->is_approved == 0){
            return view('user.pages.waitForApproved', compact('categories'));
        }else{
            return view('user.pages.services.show-service', compact('categories'));
        }

    }

    public function show()
    {
        $categories = Category::with(['service' => function ($query) {
            $query->userRate()->where('service_status', 1);
        }])
            ->where('status', 1)
            ->get();
        $user = Auth::user();
        if ($user->is_agent == 1 && $user->is_approved == 1){

            return view('agent.pages.services.show-service',compact('categories'));
        }elseif ($user->is_agent == 1 && $user->is_approved == 0){
            return view('user.pages.services.show-service', compact('categories'));
        }else{
            return view('user.pages.services.show-service', compact('categories'));
        }

    }


    public function search(Request $request)
    {
        $search = $request->all();
        $categories = Category::with('service')->where('status', 1)
            ->when(isset($search['service']), function ($query) use ($search) {
                return $query->where('category_title', 'LIKE', "%{$search['service']}%");
            })
            ->get();
        return view('user.pages.services.show-service', compact( 'categories'));
    }
    public function service($id)
    {
//dd($id);
        $category=Category::find($id);
        $services=Service::where('category_id', $id)->where('service_status',1)->get();
        $user = Auth::user();
        if ($user != null){
            foreach ($services as $service){
                if (!($service->price != null && $service->price !=0)){
                    $user_range = $user->priceRange;
                    $range = $service->service_price_ranges()->where('price_range_id',$user_range->id)->first();
                    $service->price = $range->price;
                    $service->agent_commission_rate = $range->agent_commission_rate;

                }
            }
//            if ($user->is_special == 1){
//                foreach ($services as $service){
//                    if ($service->special_price != null){
//                        $service->price = $service->special_price;
//                    }
//
//                }
//            }
        }


        return view('agent.pages.services.show-services', compact('services','category'));
    }
    public function servicesearch(Request $request)
    {
        $categories = Category::with('service')->where('status', 1)->get();
        $search = $request->all();
        $services = Service::where('service_status', 1)
            ->userRate()
            ->when(isset($search['service']), function ($query) use ($search) {
                return $query->where('service_title', 'LIKE', "%{$search['service']}%");
            })
            ->when(isset($search['category']), function ($query) use ($search) {
                return $query->where('category_id', $search['category']);
            })
            ->with(['category'])
            ->get()
            ->groupBy('category.category_title');
        $user = Auth::user();
        if ($user != null){
            if ($user->is_special == 1){
                foreach ($services as $service){
                    if ($service->special_price != null){
                        $service->price = $service->special_price;
                    }

                }
            }
        }
        return view('user.pages.services.search-service', compact('services', 'categories'));
    }

    public function getPlayerName($category,$playerid)
    {

        $category=Category::find($category);
       $url="http://sim90.com/api/getPlayerName/".$category->slug."/".$playerid;
       $token='76|HZ04dcna7KKEjEChTE9Ydhzuk1xzGTJhbo2vkLnK';
        $getPlayer = Http::withToken($token)->get($url);
        return   $result = json_decode($getPlayer, True);

//        [freefire,pubg,likee,bego,ahlanChat,pubgLite,yalla]


//        /        $categoryapi='https://as7abcard.com/pubg-files/pubg.php?action=getPlayerName&game=pubg&playerID=5262427733';
//               $header= ["ct"=>"ql18TgDgBmsvEu5aAJkypBwDgyHyjV8iJYJSmq1E4Kf9DS20PBpkjx3kDwrkPLc9v7o2NJ0LnrkVQNCwC0FQ+4/VaGKGdk60NOtd7ExY8zI=","iv"=>"0f4e33d8213109fa64a412cb07b2659d","s"=>"c5f09a65b90f316a"];
//        $getPlayer = Http::post($categoryapi,["ct"=>"ql18TgDgBmsvEu5aAJkypBwDgyHyjV8iJYJSmq1E4Kf9DS20PBpkjx3kDwrkPLc9v7o2NJ0LnrkVQNCwC0FQ+4/VaGKGdk60NOtd7ExY8zI=","iv"=>"0f4e33d8213109fa64a412cb07b2659d","s"=>"c5f09a65b90f316a"]);

    }

}

resources/views/themes/minimal/services/search-service.blade.php
@extends($theme.'layouts.app')
@section('title','Search Service')

@section('content')

    <section class="service-list">
        <div class="container-fluid px-3 user-service-list">
            <div class="row my-3 justify-content-between mx-lg-5">
                <div class="col-md-12">

                    <div class="card">
                        <div class="card-body">
                            <form action="{{ route('service.search') }}" method="get">
                                <div class="row justify-content-center">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <input type="text" name="service" value="{{@request()->service}}"
                                                   class="form-control"
                                                   placeholder="@lang('Search for Services')">
                                        </div>
                                    </div>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <select name="category" id="category" class="form-control statusfield">
                                                <option value="" >@lang('All Category')</option>
                                                @foreach($categories as $category)
                                                    <option
                                                        value="{{$category->id}}" {{($category->id == @request()->category) ? 'selected' : ''}}>@lang($category->category_title)</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>


                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary w-100 btn-padding"><i
                                                    class="fas fa-search"></i> @lang('Search')</button>
                                        </div>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>

            <div class="row my-3 justify-content-between mx-lg-5">
                <div class="col-md-12">

                    @foreach($services as $key => $service)

                        <div class="card mb-3">
                            <div class="card-body">
                                <h4 class="card-title">@lang($key)</h4>

                                <div class="table-responsive ">
                                    <table class="categories-show-table table table-hover table-striped table-bordered">
                                        <thead>
                                        <tr>
                                            <th scope="col" class="text-center">@lang('ID')</th>
                                            <th scope="col" class="text-left">@lang('Name')</th>
                                            <th scope="col"
                                                class="text-center">@lang('Rate Per 1k')')</th>
                                            <th scope="col" class="text-center">@lang('Min')</th>
                                            <th scope="col" class="text-center">@lang('Max')</th>
                                            <th scope="col" class="text-center">@lang('Description')</th>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        @foreach($service as $key => $row)
                                            <tr>
                                                <td data-label="@lang('ID')" class="text-right text-md-center">{{$row->id}}</td>
                                                <td data-label="@lang('Name')" class="text-right text-md-left">
                                                    @lang($row->service_title)
                                                </td>
                                                <td data-label="@lang('Rate Per 1000('.config('basic.currency_symbol').')')" class="text-right text-md-center">
                                                    {{($row->user_rate) ?? $row->price}}{{config('basic.currency')}}

                                                </td>
                                                <td data-label="@lang('Min')" class="text-right text-md-center">
                                                    @lang($row->min_amount)
                                                </td>
                                                <td data-label="@lang('Max')" class="text-right text-md-center">
                                                     @lang($row->max_amount)
                                                </td>
                                                <td data-label="@lang('Description')"  class="text-right text-md-center">
                                                    <button type="button" class="btn btn-info btn-sm bg-transparent text-dark btn-padding"
                                                            data-toggle="modal"
                                                            data-target="#description"
                                                            id="details"
                                                            data-servicetitle="{{$row->service_title}}"
                                                            data-id="{{$row->id}}"
                                                            data-description="{{$row->description}}"> <i class="fa fa-eye"></i> @lang('More')</button>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>


                    @endforeach
                </div>
            </div>
        </div>
    </section>



    <div class="modal fade" id="description">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title" id="title"></h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body" id="servicedescription">

                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-padding close" data-dismiss="modal">@lang('Close')</button>
                    <a href="" type="submit" class="btn btn-success btn-padding order-now">@lang('Order Now')</a>
                </div>

            </div>
        </div>
    </div>


@endsection



@push('script')
    <script>
        "use strict";
        $(document).ready(function () {
            $(document).on('click', '#details', function () {
                var title = $(this).data('servicetitle');
                var description = $(this).data('description');

                var id = $(this).data('id');
                var orderRoute = "{{route('user.order.create')}}" + '?serviceId=' + id;
                $('.order-now').attr('href', orderRoute);

                $('#title').text(title);
                $('#servicedescription').text(description);
            });
        });
    </script>
@endpush