routes/web.php
    return $output->fetch();
})->name('/clear');



Route::get('queue-work', function () {
    return Illuminate\Support\Facades\Artisan::call('queue:work', ['--stop-when-empty' => true]);
});
Route::get('schedule-run', function () {
    return Illuminate\Support\Facades\Artisan::call('schedule:run');
});

Route::get('cron', 'FrontendController@cron')->name('cron');
Route::get('/get-player-name/{playerId}/{game}', 'CustomProviderController@getPlayerName')->name('get-player-name');


Route::get('/user', 'Auth\LoginController@showLoginForm')->name('login');
Auth::routes(['verify' => true]);
Route::get('/registerAsAgent', 'Agent\HomeController@showAgentRegistrationForm')->name('registerAsAgent');
Route::Post('/registerAsAgent/{user}', 'Agent\HomeController@registerAsAgent')->name('addAgent');


Route::group(['middleware' => ['auth'], 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('/check', 'VerificationController@check')->name('check');
    Route::get('/resend_code', 'VerificationController@resendCode')->name('resendCode');
    Route::post('/mail-verify', 'VerificationController@mailVerify')->name('mailVerify');
    Route::post('/sms-verify', 'VerificationController@smsVerify')->name('smsVerify');
    Route::middleware('userCheck')->group(function () {
        Route::get('/dashboard', 'User\ServiceController@index')->name('home');
//        Route::get('/dashboard', 'HomeController@index')->name('home');
        Route::get('use_spare_balance', 'HomeController@use_spare_balance')->name('use_spare_balance');
        Route::get('add-fund', 'HomeController@addFund')->name('addFund');
        Route::post('add-fund', 'PaymentController@addFundRequest')->name('addFund.request');
        Route::get('addFundConfirm', 'PaymentController@depositConfirm')->name('addFund.confirm');
        Route::post('addFundConfirm', 'PaymentController@fromSubmit')->name('addFund.fromSubmit');

        Route::get('balance-transfer', 'HomeController@transferBalance')->name('balance.transfer');
        Route::post('transfer', 'HomeController@transfer')->name('balance-transfer');

        //transaction
        Route::get('/transaction', 'HomeController@transaction')->name('transaction');
        Route::get('/transaction-search', 'HomeController@transactionSearch')->name('transaction.search');
        Route::get('fund-history', 'HomeController@fundHistory')->name('fund-history');
        Route::get('fund-history-search', 'HomeController@fundHistorySearch')->name('fund-history.search');
        Route::get('/use-balance-coupon', 'HomeController@useBalanceCoupon')->name('use-balance-coupon');
        Route::Post('/add-balance-coupon', 'HomeController@addBalanceCoupon')->name('add-balance-coupon');

        Route::get('/user/debts', 'User\HomeController@debts')->name('debts');
        Route::get('/getLevelData', 'User\HomeController@getLevelData')->name('getLevelData');


        Route::get('/profile', 'HomeController@profile')->name('profile');
        Route::post('/updateProfile', 'HomeController@updateProfile')->name('updateProfile');
        Route::put('/updateInformation', 'HomeController@updateInformation')->name('updateInformation');
        Route::post('/updatePassword', 'HomeController@updatePassword')->name('updatePassword');

        Route::get('/apiKey', 'HomeController@apiKey')->name('apiKey');

        //order
        Route::resource('order', 'User\OrderController');
        Route::get('/orders', 'User\OrderController@search')->name('order.search');
        Route::post('/order/status', 'User\OrderController@statusChange')->name('order.status.change');
        Route::get('/orders/{status}', 'User\OrderController@statusSearch')->name('order.status.search');
        Route::get('/mass/orders', 'User\OrderController@massOrder')->name('order.mass');
        Route::post('/mass/orders', 'User\OrderController@masOrderStore')->name('order.mass.store');
        Route::get('/get-service', 'ServiceController@getservice')->name('get.service');

        //order search
        Route::get('/services', 'User\ServiceController@index')->name('service.show');
        Route::get('/products', 'User\ServiceController@show')->name('products');
        Route::get('/service-search', 'User\ServiceController@search')->name('service.search');
        Route::get('/services/{id}', 'User\ServiceController@service')->name('services.show');
        Route::get('/player/{serviceid}/{playerid}', 'User\ServiceController@getPlayerName')->name('service.player');

        Route::get('/api/docs', 'User\ApiController@index')->name('api.docs');
        Route::post('/keyGenerate', 'User\ApiController@apiGenerate')->name('keyGenerate');
        Route::get('checksms/{id}', 'ApiProviderController@checkSMS')->name('checksms');
        Route::group(['prefix' => 'ticket', 'as' => 'ticket.'], function () {
            Route::get('/', 'User\SupportController@index')->name('list');
            Route::get('/create', 'User\SupportController@create')->name('create');
            Route::post('/create', 'User\SupportController@store')->name('store');
            Route::get('/view/{ticket}', 'User\SupportController@view')->name('view');
            Route::put('/reply/{ticket}', 'User\SupportController@reply')->name('reply');
            Route::get('/download/{ticket}', 'User\SupportController@download')->name('download');
        });

        Route::post('/service', function (Request $request) {
            $parent_id = $request->cat_id;
            $services = Service::where('category_id', $parent_id)->where('service_status', 1)->get();
            return response()->json($services);
        })->name('service');


        Route::get('push-notification-show', 'SiteNotificationController@show')->name('push.notification.show');
        Route::get('push.notification.readAll', 'SiteNotificationController@readAll')->name('push.notification.readAll');
        Route::get('push-notification-readAt/{id}', 'SiteNotificationController@readAt')->name('push.notification.readAt');

        Route::get('/user-service', 'User\OrderController@userservice')->name('service_id');

        Route::get('points', 'HomeController@pointTransactions')->name('points');
        Route::get('/points-search', 'HomeController@pointTransactionsSearch')->name('points.transactions.search');
        Route::post('points-replace', 'HomeController@replacePoints')->name('points.replace');

        //Marketer
        Route::middleware('can:join_as_marketer')->group(function () {
            Route::get('marketer-join', 'MarketerController@create')->name('marketer.join');
            Route::post('marketer-join', 'MarketerController@store')->name('marketer.store');
            Route::get('random-code', 'MarketerController@getRandomInvitaionCode')->name('marketer.random-code');
            Route::post('marketer-golden-join', 'MarketerController@goldenMarketer')->name('marketer.golden.store');
        });
        Route::middleware('can:marketer')->group(function () {
            Route::get('marketers', 'MarketerController@index')->name('marketers');
            Route::middleware('can:active_marketer')->group(function () {
                Route::post('swap', 'MarketerController@swap')->name('marketer.swap')->middleware('can:normal_marketer');
                Route::post('marketer-golden-refund', 'MarketerController@goldenMareketerRefund')->name('marketer.golden.refund')->middleware('can:golden_marketer');
            });


        });
        Route::post('username', 'HomeController@getUsernameByEmail')->name('user.username');
    });
});
Route::group(['middleware' => ['auth', 'can:agent'], 'prefix' => 'agent', 'as' => 'agent.'], function () {
    Route::middleware('userCheck')->group(function () {
        Route::get('/users', 'Agent\UserController@index')->name('users');
        Route::get('/products', 'Agent\ServiceController@show')->name('products');
        Route::get('/users/search', 'Agent\UserController@search')->name('users.search');
        Route::get('/user/create', 'Agent\UserController@create')->name('user.create');
        Route::post('/user/create', 'Agent\UserController@store')->name('user.store');
        Route::get('/user/edit/{id}', 'Agent\UserController@userEdit')->name('user.edit');
        Route::post('/user/update/{id}', 'Agent\UserController@userUpdate')->name('user.update');
        Route::get('/user/add-balance', 'Agent\UserController@addBalance')->name('user.add-balance');
        Route::post('/user/add-balance', 'Agent\UserController@addBalanceToUser')->name('user.add-balance-to-user');
        Route::get('use_spare_balance', 'Agent\HomeController@use_spare_balance')->name('use_spare_balance');
        Route::get('/add-debt-payment', 'Agent\UserController@addDebtPayment')->name('add-debt-payment');
        Route::Post('/pay-a-debt', 'Agent\UserController@payDebt')->name('pay-a-debt');
        //order search
        Route::get('/services', 'Agent\ServiceController@index')->name('service.show');
        Route::get('/service-search', 'Agent\ServiceController@search')->name('service.search');
        Route::get('/services/{id}', 'Agent\ServiceController@service')->name('services.show');

        Route::get('/users/orders', 'Agent\UserController@usersOrder')->name('users.orders');
        Route::get('/users/orderSearch', 'Agent\UserController@usersOrderSearch')->name('users.OrderSearch');

        Route::get('/users/debtSearch', 'Agent\UserController@usersDebtSearch')->name('users.debtSearch');

        Route::get('/profile', 'Agent\HomeController@profile')->name('profile');
        Route::post('/updateProfile', 'Agent\HomeController@updateProfile')->name('updateProfile');
        Route::put('/updateInformation', 'Agent\HomeController@updateInformation')->name('updateInformation');
        Route::post('/updatePassword', 'Agent\HomeController@updatePassword')->name('updatePassword');

        Route::group(['prefix' => 'ticket', 'as' => 'ticket.'], function () {

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public function service()
    {
        return $this->belongsTo(Service::class, 'service_id','id');
    }

    public function agentCommissionRate()
    {
        return $this->hasOne(AgentCommissionRate::class,'order_id');
    }

    public function users()
    {
        return $this->belongsTo(User::class,'user_id','id');
    }

    public function transaction()
    {
        return $this->hasMany(Transaction::class);
    }

    public function debt()
    {
        return $this->hasMany(Debt::class,'order_id');
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id','id');
    }

    public function pointTransactions()
    {
        return $this->hasMany(PointsTransaction::class);
    }

    public function admin()
    {
        return $this->belongsTo(Admin::class,'updated_by');

    }
}

resources/views/admin/pages/order/edit.blade.php
@extends('admin.layouts.app')
@section('title')
    @lang('Edit Order')
@endsection
@section('content')

    <div class="card card-primary m-0 m-md-4 my-4 m-md-0 shadow">
        <div class="card-body">
            <form method="post" action="{{route('admin.order.update',$order->id)}}" enctype="multipart/form-data">

                @csrf
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label" for="category_id">@lang('Category')</label>
                            <select class="form-control" id="category" name="category_id" disabled>
                                @foreach($categories as $category)
                                    <option
                                            value="{{$category->id}}" {{ ($order->category_id == $category->id) ? 'selected' : ''}}>{{ $category->category_title  }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group ">
                            <label>@lang('Quantity')</label>
                            <input type="number" name="quantity" id="quantity" value="{{ $order->quantity }}"
                                   class="form-control" disabled>
                            <div class="invalid-feedback">@lang('Please fill in the link')</div>
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="service_id">@lang('Service')</label>
                            <select class="form-control" name="service_id" id="service" disabled>
                                @foreach($category->service as $service)
                                    <option
                                            value="{{$service->id}}" {{ ($order->service_id == $service->id) ? 'selected' : '' }} >{{ $service->service_title  }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group ">
                            <label>@lang('Runs')</label>
                            <input type="number" name="runs" value="{{ old('link',$order->runs) }}" placeholder="runs"
                                   class="form-control runs" disabled>
                            <div class="invalid-feedback">@lang('Please fill in the link')</div>
                        </div>
                        <div class="form-group ">
                            <label>@lang('Start Counter')</label>
                            <input type="number" name="start_counter" value="{{ old('link',$order->start_counter) }}"
                                   placeholder="start counter" class="form-control" disabled>
                            <div class="invalid-feedback">@lang('Please fill in the link')</div>
                        </div>
                        <div class="form-group ">
                            <label>@lang('Status Description')</label>
                            <textarea class="form-control" disabled>{{ $order->status_description }}</textarea>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group ">
                            <label>@lang('Link')</label>
                            <input type="text" name="link" value="{{ old('link',$order->link) }}"
                                   placeholder="www.example.com/your_profile_identity" class="form-control">
                        </div>
                        <div class="form-group ">
                            <label>@lang('Interval')</label>
                            <input type="number" name="interval" value="{{ old('interval',$order->interval) }}"
                                   placeholder="interval" class="form-control" disabled>
                            <div class="invalid-feedback">@lang('Please fill in the link')</div>
                        </div>
                        <div class="form-group ">
                            <label>@lang('Remains')</label>
                            <input type="number" name="remains" value="{{ old('remains',$order->remains) }}"
                                   placeholder="remains" class="form-control">
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>@lang('Start counter')</label>
                                    <input class="form-control" type="number" name="start_counter" id="start_counter"
                                           value="{{ old('start_counter',$order->start_counter) }}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>@lang('API Order ID')</label>
                                    <input class="form-control" type="text" name="api_order_id" id="api_order_id"
                                           value="{{ old('api_order_id',$order->api_order_id) }}">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>@lang('Change Status')</label>
                            <select class="form-control" id="status" name="status">
                                <option value="{{$order->status}}" disabled selected>
                                    @if($order->status=='awaiting') {{'Awaiting'}}
                                    @elseif($order->status == 'pending') {{'Pending'}}
                                    @elseif($order->status == 'processing') {{'Processing'}}
                                    @elseif($order->status == 'progress') {{'In progress'}}
                                    @elseif($order->status == 'completed') {{'Completed'}}
                                    @elseif($order->status == 'partial') {{'Partial'}}
                                    @elseif($order->status == 'canceled') {{'Canceled'}}
                                    @elseif($order->status == 'refunded') {{'Refunded'}}
                                    @elseif($order->status == 'code-waiting') {{'Waiting for Code'}}
                                    @endif
                                </option>
                                <option value="awaiting">@lang('Awaiting')</option>
                                <option value="pending">@lang('Pending')</option>
                                <option value="processing">@lang('Processing')</option>
                                {{--<option value="progress">@lang('In progress')</option>--}}
                                <option value="completed">@lang('Completed')</option>
                                @if(auth()->user()->role!='SellMan')
                                    <option value="partial">@lang('Partial')</option>
                                    <option value="canceled">@lang('Canceled')</option>
                                    <option value="refunded">@lang('Refunded')</option>
                                @endif
                            </select>
                            <div class="invalid-feedback">@lang('Please fill in the Service Type')</div>
                        </div>
                        <div class="form-group ">
                            <label>@lang('Note')</label>
                            <textarea class="form-control" name="reason">{{ $order->reason }}</textarea>
                        </div>
                    </div>
                </div>
                <div class="submit-btn-wrapper mt-md-5 text-center text-md-left">
                    <button type="submit" class=" btn  btn-primary btn-block mt-3">
                        <span>@lang('Submit')</span></button>
                </div>
            </form>

        </div>
    </div>
@endsection
@push('extra-script')
    <script>
        "use strict";
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $(document).ready(function () {
            $('#category').on('change', function (e) {
                let cat_id = $('option:selected', this).val();
                // console.log(cat_id)
                $.ajax({
                    url: "{{ route('admin.service') }}",
                    type: "POST",
                    data: {cat_id: cat_id},
                    success: function (data) {
                        $('#service').html('');
                        if (data.length) {
                            $(data).each(function (key, val) {
                                if (key == 0) {
                                    $('#service').append('<option value="" disabled selected>Select Service</option>');
                                }
                                $('#service').append('<option value="' + val.id + '">' + val.service_title + '</option>');
                            });
                        }
                    }
                })
            });

        });
    </script>
@endpush

resources/views/admin/pages/order/search.blade.php
@extends('admin.layouts.app')
@section('title')
    @lang($page_title)
@endsection

@section('content')


    @include('admin.pages.order.partials.search-bar')

    <div class="card card-primary m-0 m-md-4 my-4 m-md-0 shadow">
        <div class="card-body">

        <div class="table-responsive">
            <table class="categories-show-table table table-hover table-striped table-bordered">
                <thead class="thead-primary">
                    <tr>
                        <th scope="col" class="text-center">
                            <input type="checkbox" class="form-check-input check-all tic-check" name="check-all"
                                id="check-all">
                            <label for="check-all"></label>
                        </th>
                        <th scope="col">@lang('Order No.')</th>
                        <th scope="col">@lang('User')</th>
                        <th scope="col">@lang('Order Details')</th>
                        <th scope="col">@lang('Service Details')</th>
                        <th scope="col">@lang('Created')</th>
                        <th scope="col">@lang('Status')</th>
                        <th scope="col">@lang('Action')</th>
                    </tr>
                </thead>
                <tbody>
                @forelse($orders as $order)
                    <tr>
                        <td class="text-center">
                            <input type="checkbox" id="chk-{{ $order->id }}" class="form-check-input row-tic tic-check"
                                   name="check" value="{{ $order->id }}" data-id="{{ $order->id }}">
                            <label for="chk-{{ $order->id }}"></label>
                        </td>

                        <td data-label="@lang('Order No.')">{{$order->id}}</td>
                        <td data-label="@lang('User')">
                            <a href="{{route('admin.user-edit',$order->user_id)}}" target="_blank">
                                @lang(optional($order->users)->username)
                            </a>
                        </td>
                        <td data-label="@lang('Order Details')">
                            <h5>{{ optional($order->service)->service_title }}</h5>
                            @lang('Link:') {{ $order->link }}<br>
                            @lang('quantity:') {{ $order->quantity }} <br>
                            @lang("Start counter:")<br>
                            @lang('Remains:')<br>
                            <span
                                onclick="copy('{{$order->service->service_title}} \n @lang('Link'): @lang($order->link)\n @lang('Quantity'): @lang($order->quantity)  \n @lang('Category'): @lang(optional($order->service)->category->category_title)')">
                                    <i class="fa fa-copy" style="font-size: 25px;"></i>
                                </span>
                        </td><td data-label="@lang('Service Details')">
                            <h5>@lang(optional($order->service)->service_title) </h5>
                            @lang('Category'): @lang(optional($order->service)->category->category_title)<br>
                            @lang('order price'): {{$order->price}} {{config('basic.currency_symbol')}}<br>
                            @lang('service price'): {{$order->service->price}} {{config('basic.currency_symbol')}}<br>

                        </td>

                        <td data-label="@lang('Created')">{{dateTime($order->created_at , 'd M Y, h:i A')}} </td>
                        <td data-label="@lang('Status')">

                            @if($order->status=='awaiting')
                                <span class="badge badge-pill badge-danger">{{'Awaiting'}}</span>
                            @elseif($order->status == 'pending') <span
                                    class="badge badge-pill badge-info">{{'Pending'}}</span>
                            @elseif($order->status == 'processing') <span
                                    class="badge badge-pill badge-info">{{'Processing'}}</span>
                            @elseif($order->status == 'progress') <span
                                    class="badge badge-pill badge-warning">{{'In progress'}}</span>
                            @elseif($order->status == 'completed') <span
                                    class="badge badge-pill badge-success">{{'Completed'}}</span>
                            @elseif($order->status == 'partial') <span
                                    class="badge badge-pill badge-warning">{{'Partial'}}</span>
                            @elseif($order->status == 'canceled') <span
                                    class="badge badge-pill badge-danger">{{'Canceled'}}</span>
                            @elseif($order->status == 'refunded') <span
                                    class="badge badge-pill badge-danger">{{'Refunded'}}</span>
                            @elseif($order->status == 'code-waiting') <span
                                    class="badge badge-pill badge-danger">{{'Waiting for Code'}}</span>
                            @endif
                        </td>

                        <td data-label="@lang('Action')">
                            <div class="dropdown show">
                                <a class="dropdown-toggle p-3" href="#" id="dropdownMenuLink" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <a class="dropdown-item"
                                       href="{{ route('admin.order.edit',[$order->id]) }}"><i
                                                class="fa fa-edit text-warning pr-2"
                                                aria-hidden="true"></i> @lang('Edit')
                                    </a>
                                    <a href="javascript:void(0)" class="dropdown-item status-change" data-toggle="modal" data-target="#statusMoldal" data-route="{{ route('admin.order.status.change',['id'=>$order->id] ) }} " >
                                        <i class="fa fa-check pr-2 text-success" aria-hidden="true"></i> @lang('Change Status')
                                    </a>

                                    <a href="javascript:void(0)" class="dropdown-item delete-order" data-toggle="modal"
                                       data-target="#deleteModal"
                                       data-route="{{ route('admin.order.destroy',[$order->id])}} ">
                                        <i class="fa fa-trash-alt pr-2 text-danger"
                                           aria-hidden="true"></i> @lang('Delete')
                                    </a>


                                </div>
                            </div>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="100%">@lang('No Data Found!')</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
            {{ $orders->appends($_GET)->links() }}
        </div>
    </div>

    </div>


    @include('admin.pages.order.partials.modal')
@endsection

@push('js')
    <script>
        $(document).ready(function(){
            "use strict";
            $(document).on('click', '#check-all', function () {
                $('input:checkbox').not(this).prop('checked', this.checked);
            });

            $(document).on('change', ".row-tic", function () {
                let length = $(".row-tic").length;
                let checkedLength = $(".row-tic:checked").length;
                if (length == checkedLength) {
                    $('#check-all').prop('checked', true);
                } else {
                    $('#check-all').prop('checked', false);
                }
            });

            $(document).on('click', '.status-change', function () {
                let route = $(this).data('route');
                $('#statusForm').attr('action', route);
            });

            $(document).on('click', '.delete-order', function () {
                let route = $(this).data('route');
                $('#deleteConfirm').attr('action', route);
            });

            $(document).on('click','.dropdown-menu',function(e){
                e.stopPropagation();
            });


            //all checked click function

            $(document).on('click', '.usersOrderChangeStatus', function () {
                status = $(this).data('status');
            });

            $(document).on('click', '.awaiting-yes', function (e) {
                e.preventDefault();
                var allVals = [];

                $(".row-tic:checked").each(function () {
                    allVals.push($(this).attr('data-id'));
                });

                var strIds = allVals.join(",");
                $.ajax({
                    headers: {'X-CSRF-TOKEN': $('meta[name="csrf_token"]').attr('content')},
                    url: "{{ route('admin.usersOrderChangeStatus') }}",
                    data: {
                        strIds,
                        status
                    },
                    datatType: 'json',
                    type: "get",
                    success: function (data) {
                        location.reload();
                    }
                });
            })




        });

        function copy($link) {
            /* Copy the text inside the text field */
            console.log($link)
            navigator.clipboard.writeText($link);

            Toastify({
                text: "تم النسخ",
                duration: 3000
            }).showToast();
        }


    </script>
@endpush