routes/web.php
<?php

use App\Models\Service;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Artisan;

Route::get('/clear', function () {
    $output = new \Symfony\Component\Console\Output\BufferedOutput();
    Artisan::call('optimize:clear', array(), $output);
    return $output->fetch();
})->name('/clear');



Route::get('queue-work', function () {
    return Illuminate\Support\Facades\Artisan::call('queue:work', ['--stop-when-empty' => true]);
});
Route::get('schedule-run', function () {
    return Illuminate\Support\Facades\Artisan::call('schedule:run');
});

Route::get('cron', 'FrontendController@cron')->name('cron');
Route::get('/get-player-name/{playerId}/{game}', 'CustomProviderController@getPlayerName')->name('get-player-name');


Route::get('/user', 'Auth\LoginController@showLoginForm')->name('login');
Auth::routes(['verify' => true]);
Route::get('/registerAsAgent', 'Agent\HomeController@showAgentRegistrationForm')->name('registerAsAgent');
Route::Post('/registerAsAgent/{user}', 'Agent\HomeController@registerAsAgent')->name('addAgent');


Route::group(['middleware' => ['auth'], 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('/check', 'VerificationController@check')->name('check');
    Route::get('/resend_code', 'VerificationController@resendCode')->name('resendCode');
    Route::post('/mail-verify', 'VerificationController@mailVerify')->name('mailVerify');
    Route::post('/sms-verify', 'VerificationController@smsVerify')->name('smsVerify');
    Route::middleware('userCheck')->group(function () {
        Route::get('/dashboard', 'User\ServiceController@index')->name('home');
//        Route::get('/dashboard', 'HomeController@index')->name('home');
        Route::get('use_spare_balance', 'HomeController@use_spare_balance')->name('use_spare_balance');
        Route::get('add-fund', 'HomeController@addFund')->name('addFund');
        Route::post('add-fund', 'PaymentController@addFundRequest')->name('addFund.request');
        Route::get('addFundConfirm', 'PaymentController@depositConfirm')->name('addFund.confirm');
        Route::post('addFundConfirm', 'PaymentController@fromSubmit')->name('addFund.fromSubmit');

        Route::get('balance-transfer', 'HomeController@transferBalance')->name('balance.transfer');
        Route::post('transfer', 'HomeController@transfer')->name('balance-transfer');

        //transaction
        Route::get('/transaction', 'HomeController@transaction')->name('transaction');
        Route::get('/transaction-search', 'HomeController@transactionSearch')->name('transaction.search');
        Route::get('fund-history', 'HomeController@fundHistory')->name('fund-history');
        Route::get('fund-history-search', 'HomeController@fundHistorySearch')->name('fund-history.search');
        Route::get('/use-balance-coupon', 'HomeController@useBalanceCoupon')->name('use-balance-coupon');
        Route::Post('/add-balance-coupon', 'HomeController@addBalanceCoupon')->name('add-balance-coupon');

        Route::get('/user/debts', 'User\HomeController@debts')->name('debts');
        Route::get('/getLevelData', 'User\HomeController@getLevelData')->name('getLevelData');


        Route::get('/profile', 'HomeController@profile')->name('profile');
        Route::post('/updateProfile', 'HomeController@updateProfile')->name('updateProfile');
        Route::put('/updateInformation', 'HomeController@updateInformation')->name('updateInformation');
        Route::post('/updatePassword', 'HomeController@updatePassword')->name('updatePassword');

        Route::get('/apiKey', 'HomeController@apiKey')->name('apiKey');

        //order
        Route::resource('order', 'User\OrderController');
        Route::get('/orders', 'User\OrderController@search')->name('order.search');
        Route::post('/order/status', 'User\OrderController@statusChange')->name('order.status.change');
        Route::get('/orders/{status}', 'User\OrderController@statusSearch')->name('order.status.search');
        Route::get('/mass/orders', 'User\OrderController@massOrder')->name('order.mass');
        Route::post('/mass/orders', 'User\OrderController@masOrderStore')->name('order.mass.store');
        Route::get('/get-service', 'ServiceController@getservice')->name('get.service');

        //order search
        Route::get('/services', 'User\ServiceController@index')->name('service.show');
        Route::get('/products', 'User\ServiceController@show')->name('products');
        Route::get('/service-search', 'User\ServiceController@search')->name('service.search');
        Route::get('/services/{id}', 'User\ServiceController@service')->name('services.show');
        Route::get('/player/{serviceid}/{playerid}', 'User\ServiceController@getPlayerName')->name('service.player');

        Route::get('/api/docs', 'User\ApiController@index')->name('api.docs');
        Route::post('/keyGenerate', 'User\ApiController@apiGenerate')->name('keyGenerate');
        Route::get('checksms/{id}', 'ApiProviderController@checkSMS')->name('checksms');
        Route::group(['prefix' => 'ticket', 'as' => 'ticket.'], function () {
            Route::get('/', 'User\SupportController@index')->name('list');
            Route::get('/create', 'User\SupportController@create')->name('create');
            Route::post('/create', 'User\SupportController@store')->name('store');
            Route::get('/view/{ticket}', 'User\SupportController@view')->name('view');
            Route::put('/reply/{ticket}', 'User\SupportController@reply')->name('reply');
            Route::get('/download/{ticket}', 'User\SupportController@download')->name('download');
        });

        Route::post('/service', function (Request $request) {
            $parent_id = $request->cat_id;
            $services = Service::where('category_id', $parent_id)->where('service_status', 1)->get();
            return response()->json($services);
        })->name('service');


        Route::get('push-notification-show', 'SiteNotificationController@show')->name('push.notification.show');
        Route::get('push.notification.readAll', 'SiteNotificationController@readAll')->name('push.notification.readAll');
        Route::get('push-notification-readAt/{id}', 'SiteNotificationController@readAt')->name('push.notification.readAt');

        Route::get('/user-service', 'User\OrderController@userservice')->name('service_id');

        Route::get('points', 'HomeController@pointTransactions')->name('points');
        Route::get('/points-search', 'HomeController@pointTransactionsSearch')->name('points.transactions.search');
        Route::post('points-replace', 'HomeController@replacePoints')->name('points.replace');

        //Marketer
        Route::middleware('can:join_as_marketer')->group(function () {
            Route::get('marketer-join', 'MarketerController@create')->name('marketer.join');
            Route::post('marketer-join', 'MarketerController@store')->name('marketer.store');
            Route::get('random-code', 'MarketerController@getRandomInvitaionCode')->name('marketer.random-code');
            Route::post('marketer-golden-join', 'MarketerController@goldenMarketer')->name('marketer.golden.store');
        });
        Route::middleware('can:marketer')->group(function () {
            Route::get('marketers', 'MarketerController@index')->name('marketers');
            Route::middleware('can:active_marketer')->group(function () {
                Route::post('swap', 'MarketerController@swap')->name('marketer.swap')->middleware('can:normal_marketer');
                Route::post('marketer-golden-refund', 'MarketerController@goldenMareketerRefund')->name('marketer.golden.refund')->middleware('can:golden_marketer');
            });


        });
        Route::post('username', 'HomeController@getUsernameByEmail')->name('user.username');
    });
});
Route::group(['middleware' => ['auth', 'can:agent'], 'prefix' => 'agent', 'as' => 'agent.'], function () {
    Route::middleware('userCheck')->group(function () {
        Route::get('/users', 'Agent\UserController@index')->name('users');
        Route::get('/products', 'Agent\ServiceController@show')->name('products');
        Route::get('/users/search', 'Agent\UserController@search')->name('users.search');
        Route::get('/user/create', 'Agent\UserController@create')->name('user.create');
        Route::post('/user/create', 'Agent\UserController@store')->name('user.store');
        Route::get('/user/edit/{id}', 'Agent\UserController@userEdit')->name('user.edit');
        Route::post('/user/update/{id}', 'Agent\UserController@userUpdate')->name('user.update');
        Route::get('/user/add-balance', 'Agent\UserController@addBalance')->name('user.add-balance');
        Route::post('/user/add-balance', 'Agent\UserController@addBalanceToUser')->name('user.add-balance-to-user');
        Route::get('use_spare_balance', 'Agent\HomeController@use_spare_balance')->name('use_spare_balance');
        Route::get('/add-debt-payment', 'Agent\UserController@addDebtPayment')->name('add-debt-payment');
        Route::Post('/pay-a-debt', 'Agent\UserController@payDebt')->name('pay-a-debt');
        //order search
        Route::get('/services', 'Agent\ServiceController@index')->name('service.show');
        Route::get('/service-search', 'Agent\ServiceController@search')->name('service.search');
        Route::get('/services/{id}', 'Agent\ServiceController@service')->name('services.show');

        Route::get('/users/orders', 'Agent\UserController@usersOrder')->name('users.orders');
        Route::get('/users/orderSearch', 'Agent\UserController@usersOrderSearch')->name('users.OrderSearch');

        Route::get('/users/debtSearch', 'Agent\UserController@usersDebtSearch')->name('users.debtSearch');

        Route::get('/profile', 'Agent\HomeController@profile')->name('profile');

resources/views/agent/pages/transaction/fundHistory.blade.php
@extends('agent.layouts.app')
@section('title')
    @lang('Fund History')
@endsection
@section('content')
     <div class="container px-3 user-service-list order-list">



        <div class="row justify-content-between">
            <div class="col-md-12">

                <ol class="breadcrumb center-items">
                    <li><a href="{{route('user.home')}}">@lang('Home')</a></li>
                    <li class="active">@lang('Fund History')</li>
                </ol>

                <div class="card my-3">
                    <div class="card-body">

                        <form action="{{ route('agent.fund-history.search') }}" method="get">
                            <div class="row justify-content-between align-items-center">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input type="text" name="name" value="{{@request()->name}}" class="form-control"
                                               placeholder="@lang('Type Here')">
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <select name="status" class="form-control">
                                            <option value="">@lang('All Payment')</option>
                                            <option value="1"
                                                    @if(@request()->status == '1') selected @endif>@lang('Complete Payment')</option>
                                            <option value="2"
                                                    @if(@request()->status == '2') selected @endif>@lang('Pending Payment')</option>
                                            <option value="3"
                                                    @if(@request()->status == '3') selected @endif>@lang('Cancel Payment')</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input type="date" class="form-control" name="date_time" id="datepicker"/>
                                    </div>
                                </div>


                                <div class="col-md-3">
                                    <div class="form-group">
                                        <button style="padding:12px 30px;margin:0"
                                        type="submit" class="btn waves-effect waves-light w-100 btn-primary"><i
                                                class="fas fa-search"></i> @lang('Search')</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row my-3 justify-content-between mx-lg-5">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body ">

                            <div class="table-responsive">
                            <table class="table table-striped " id="service-table">
                                <thead>
                                <tr>
                                    <th scope="col">@lang('Transaction ID')</th>
                                    <th scope="col">@lang('Gateway')</th>
                                    <th scope="col">@lang('Amount')</th>
                                    <th scope="col">@lang('Charge')</th>
                                    <th scope="col">@lang('Status')</th>
                                    <th scope="col">@lang('Time')</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($funds as $data)
                                    <tr>

                                        <td data-label="#@lang('Transaction ID')">{{$data->transaction}}</td>
                                        @if($data->gateway_id == null)
                                            <td data-label="@lang('Gateway')">@lang('يدوي')</td>

                                        @else
                                        <td data-label="@lang('Gateway')">@lang(optional($data->gateway)->name)</td>
                                        @endif
                                        <td data-label="@lang('Amount')">
                                            <strong>{{getAmount($data->amount)}} @lang($basic->currency)</strong>
                                        </td>

                                        <td data-label="@lang('Charge')">
                                            <strong>{{getAmount($data->charge)}} @lang($basic->currency)</strong>
                                        </td>

                                        <td data-label="@lang('Status')">
                                            @if($data->status == 1)
                                                <span class="badge badge-success badge-pill">@lang('Complete')</span>
                                            @elseif($data->status == 2)
                                                <span class="badge badge-warning badge-pill">@lang('Pending')</span>
                                            @elseif($data->status == 3)
                                                <span class="badge badge-danger badge-pill">@lang('Cancel')</span>
                                            @endif
                                        </td>

                                        <td data-label="@lang('Time')">
                                            {{ dateTime($data->created_at, 'd M Y h:i A') }}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                            </div>
                            {{ $funds->appends($_GET)->links() }}


                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/agent/pages/transaction/index.blade.php
@extends('agent.layouts.app')
@section('title')
    @lang('Transaction')
@endsection
@section('content')
     <div class="container px-3 user-service-list order-list">

         <div class="row justify-content-between ">
             <div class="col-md-12">

                 <ol class="breadcrumb center-items">
                     <li><a href="{{route('user.home')}}">@lang('Home')</a></li>
                     <li class="active">@lang('Transaction')</li>
                 </ol>

                <div class="card my-3">
                    <div class="card-body">
                        <form action="{{route('agent.transaction.search')}}" method="get">
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input type="text" name="transaction_id" value="{{@request()->transaction_id}}" class="form-control get-trx-id"
                                               placeholder="@lang('Search for Transaction ID')">
                                    </div>
                                </div>


                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input type="text" name="remark" value="{{@request()->remark}}" class="form-control get-service"
                                               placeholder="@lang('Remark')">
                                    </div>
                                </div>



                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input type="date" class="form-control" name="datetrx" id="datepicker"/>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <button style="padding: 12px 15px;margin: 0;"
                                        type="submit" class="btn waves-effect waves-light w-100 btn-primary"><i class="fas fa-search"></i> @lang('Search')</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
             </div>
         </div>


        <div class="row my-3 justify-content-between">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body ">

                            <div class="table-responsive">
                            <table class="table  table-striped " id="service-table">
                                <thead>
                                <tr>
                                    <th>@lang('SL No.')</th>
                                    <th >@lang('Transaction ID')</th>
                                    <th >@lang('Amount')</th>
                                    <th >@lang('Remarks')</th>
                                    <th>@lang('Time')</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($transactions as $transaction)
                                    <tr>
                                        <td data-label="@lang('SL No.')">{{loopIndex($transactions) + $loop->index}}</td>
                                        <td data-label="@lang('Transaction ID')">@lang($transaction->trx_id)</td>
                                        <td data-label="@lang('Amount')">
                                        <span
                                            class="font-weight-bold text-{{($transaction->trx_type == "+") ? 'success': 'danger'}}">{{($transaction->trx_type == "+") ? '+': '-'}}{{getAmount($transaction->amount, config('basic.fraction_number')). ' ' . trans(config('basic.currency'))}}</span>
                                        </td>
                                        <td data-label="@lang('Remarks')"> @lang($transaction->remarks)</td>
                                        <td data-label="@lang('Time')">
                                            {{ dateTime($transaction->created_at, 'd M Y h:i A') }}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>

                            </div>
                             {{ $transactions->appends($_GET)->links() }}


                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('extra-script')
@endpush